# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ptt_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('board', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('tm', models.BigIntegerField(null=True)),
                ('update_tm', models.BigIntegerField(null=True)),
                ('likes_count', models.IntegerField(default=0, null=True)),
                ('comments_count', models.IntegerField(default=0, null=True)),
                ('dislikes_count', models.IntegerField(default=0, null=True)),
                ('keyword_match', models.TextField(null=True)),
                ('match_flag', models.IntegerField(null=True)),
                ('positive', models.IntegerField(default=0, null=True)),
                ('negative', models.IntegerField(default=0, null=True)),
                ('keywords', jsonfield.fields.JSONField(null=True)),
                ('replies', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
