# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_ptt_main_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt_main',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
