# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_ptt_main_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt_main',
            name='push_keywords',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
