# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_ptt_main_push_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptt_main',
            name='push_keywords',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
