# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20161028_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='disp_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('title', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
                ('board', models.CharField(max_length=100, null=True)),
                ('tm', models.BigIntegerField(null=True)),
                ('ip', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ptt_main',
            name='keywords',
        ),
    ]
